listen_addr: ":8080"
meta_path: "./meta.db"
storages:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"
  - "http://localhost:8084"
  - "http://localhost:8085"
  - "http://localhost:8086"
