listen_addr: ":8080"
meta_dsn: "postgres://storage:storage@localhost:5432/storage_lite?sslmode=disable"
# meta_dsn: "memory://local-dev"
storages:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"
  - "http://localhost:8084"
  - "http://localhost:8085"
  - "http://localhost:8086"
