listen_addr: ":8080"
meta_dsn: "postgres://storage:storage@localhost:5432/storage_lite?sslmode=disable"
storages:
  - "http://storage1:8081"
  - "http://storage2:8081"
  - "http://storage3:8081"
  - "http://storage4:8081"
  - "http://storage5:8081"
  - "http://storage6:8081"

